version: '3.3'

services:
  app:
    build:
      context: ./docker/node
      dockerfile: dockerfile
    image: nodejs
    container_name: simple-blog_app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./app:/usr/app"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    container_name: simple-blog_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATA=/data/postgres
    volumes:
      - "./data/postgres:/data/postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
